# This will start a haproxy and three web services. haproxy will act as a loadbalancer.
version: '3'

services:
    weba:
        build: ./web
        expose:
            - 80
        stdin_open: true
        tty: true
        networks:
           - web

    webb:
        build: ./web
        expose:
            - 80
        stdin_open: true
        tty: true
        networks:
            - web

    webc:
        build: ./web
        expose:
            - 80
        stdin_open: true
        tty: true
        networks:
            - web

    client:
        image: python:3.6

    haproxy:
        build: ./haproxy
        # image: haproxy:1.5.18
        # volumes:
        #     - ./haproxy:/haproxy-override
        #     - ./haproxy/haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg:ro
        depends_on:
            - weba
            - webb
            - webc
        ports:
            - "80:80"
            - "70:70"
        networks:
            - web

        stdin_open: true
        tty: true

networks:
  web:
